from enum import Enum


class Signal(Enum):

    USER_EXISTS = 1
    USER_DOES_NOT_EXIST = 2
    USER_AUTHORIZED = 3
    USER_DOES_NOT_AUTHORIZED = 4
    ITEM_EXISTS = 5
    ITEM_DOES_NOT_EXIST = 6
    USER_IS_RESTRICTED = 7
    USER_IS_NOT_RESTRICTED = 8
    USER_IS_BANNED = 9
    USER_IS_NOT_BANNED = 10

